const FETCH_REQUEST_START = 'FETCH_REQUEST_START';
const FETCH_REQUEST_SUCCESS = 'FETHC_REQUEST_SUCCESS';
const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';

const FETCH_REQUEST_LATEST_POSTS = 'posts_list/FETCH_REQUEST_MENU';
const FETCH_REQUEST_POSTS_BY_ID = 'post_by_id/FETCH_REQUEST_POSTS_BY_ID';

export default {
  FETCH_REQUEST_START,
  FETCH_REQUEST_SUCCESS,
  FETCH_REQUEST_ERROR,
  FETCH_REQUEST_LATEST_POSTS,
  FETCH_REQUEST_POSTS_BY_ID,
};
